#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld.shlib(features='cxx cxxshlib')
    obj.source = ['message.cc', 'socket_server.cc', 'socket_client.cc']
    obj.target = 'dawflow_ipc'
    obj.name = 'libdawflow_ipc'
    obj.includes = ['.']
    obj.export_includes = ['.']
    obj.install_path = bld.env['LIBDIR']
