#!/usr/bin/env python
from waflib.extras import autowaf as autowaf

def options(opt):
    pass

def configure(conf):
    autowaf.check_pkg(conf, 'libarchive', uselib_store='ARCHIVE', atleast_version='3.0.0', mandatory=True)

def build(bld):
    obj = bld.shlib(features='cxx cxxshlib')
    obj.source = ['message.cc', 'socket_server.cc', 'socket_client.cc', 'plugin_manifest.cc', 'plugin_loader.cc']
    obj.target = 'dawflow_ipc'
    obj.name = 'libdawflow_ipc'
    obj.includes = ['.']
    obj.export_includes = ['.']
    obj.uselib = 'ARCHIVE'
    obj.install_path = bld.env['LIBDIR']
